name: 'Build With Muddler'
description: 'Build your Mudlet project using muddler'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  package-name:
    description: 'Name of the package to upload'
    required: true
runs:
  using: "composite"
  steps:
    - id: muddler-version
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        owner: demonnic
        repo: muddler
        excludes: prerelease, draft
      
    - uses: actions/checkout@v2
    
    - name: Retrieve muddler
      run: |
        curl -L https://github.com/demonnic/muddler/releases/download/0.5/muddle-shadow-${{ steps.muddler-version.outputs.release }}.tar --output muddler.tar
        mkdir muddler-tmp
        tar xf muddler.tar -C muddler-tmp
        mv muddler-tmp/muddle-shadow-${{ steps.muddler-version.outputs.release }} muddler
        rm -rf muddler-tmp muddler.tar
      shell: bash
      
    - name: Build package with muddler
      run: |
        muddler/bin/muddle
      shell: bash
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.package-name }}
        path: build/tmp/
